### ISSUE TITLE
Exception: org.apache.uima.jcas.tcas.Annotation was not declared in the XML type descriptor (ctakes-ytex-uima)

### ISSUE THREAD

**Issue by silwalr** [apache/ctakes#23]
Hi all,

I am running into `type Annotation was not declared in the XML descriptor` error with ctakes-6.0-SNAPSHOT when using `org.apache.ctakes.ytex.uima.annotators.DBConsumer` in a pipeline. 

ERROR trace:
```org.apache.uima.analysis_engine.AnalysisEngineProcessException: Annotator processing failed.    
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:411)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.processAndOutputNewCASes(PrimitiveAnalysisEngine_impl.java:295)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:590)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:422)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:352)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:276)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.processUntilNextOutputCas(ASB_impl.java:590)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl$AggregateCasIterator.<init>(ASB_impl.java:422)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.process(ASB_impl.java:352)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.processAndOutputNewCASes(AggregateAnalysisEngine_impl.java:276)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.process(AnalysisEngineImplBase.java:295)
	at org.apache.uima.fit.pipeline.SimplePipeline.runPipeline(SimplePipeline.java:193)
	at org.apache.ctakes.core.pipeline.PipelineBuilder.run(PipelineBuilder.java:412)
	at org.apache.ctakes.core.pipeline.PiperFileRunner.run(PiperFileRunner.java:83)
	at org.apache.ctakes.core.pipeline.PiperFileRunner.main(PiperFileRunner.java:31)
Caused by: org.apache.uima.cas.CASRuntimeException: JCas type "org.apache.uima.jcas.tcas.Annotation" used in Java code,  but was not declared in the XML type descriptor.
	at org.apache.uima.cas.impl.TypeSystemImpl.throwMissingUIMAtype(TypeSystemImpl.java:2739)
	at org.apache.uima.cas.impl.TypeSystemImpl.getJCasRegisteredType(TypeSystemImpl.java:2715)
	at org.apache.uima.jcas.impl.JCasImpl.getCasType(JCasImpl.java:262)
	at org.apache.uima.jcas.impl.JCasImpl.getAnnotationIndex(JCasImpl.java:1145)
	at org.apache.ctakes.ytex.uima.mapper.DocumentMapperServiceImpl.saveAnnoBaseHib(DocumentMapperServiceImpl.java:840)
	at org.apache.ctakes.ytex.uima.mapper.DocumentMapperServiceImpl.saveAnnotationsHib(DocumentMapperServiceImpl.java:1302)
	at org.apache.ctakes.ytex.uima.mapper.DocumentMapperServiceImpl$12.doInTransaction(DocumentMapperServiceImpl.java:1432)
	at org.apache.ctakes.ytex.uima.mapper.DocumentMapperServiceImpl$12.doInTransaction(DocumentMapperServiceImpl.java:1423)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.apache.ctakes.ytex.uima.mapper.DocumentMapperServiceImpl.saveDocument(DocumentMapperServiceImpl.java:1423)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at jdk.proxy2/jdk.proxy2.$Proxy84.saveDocument(Unknown Source)
	at org.apache.ctakes.ytex.uima.annotators.DBConsumer.process(DBConsumer.java:149)
	at org.apache.uima.analysis_component.JCasAnnotator_ImplBase.process(JCasAnnotator_ImplBase.java:50)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.lambda$callProcessMethod$3(AnalysisEngineImplBase.java:669)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.withContexts(AnalysisEngineImplBase.java:698)
	at org.apache.uima.analysis_engine.impl.AnalysisEngineImplBase.callProcessMethod(AnalysisEngineImplBase.java:668)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.callAnalysisComponentProcess(PrimitiveAnalysisEngine_impl.java:383)
	... 14 more
```

I am using the most recent version of ctakes available in github, and java17. 
```
openjdk version "17.0.10" 2024-01-16
OpenJDK Runtime Environment Temurin-17.0.10+7 (build 17.0.10+7)
OpenJDK 64-Bit Server VM Temurin-17.0.10+7 (build 17.0.10+7, mixed mode, sharing)
```

I tried to implement a work around by following the workarounds provided here: 
- https://github.com/ClearTK/cleartk/issues/470 
- ctakes-core/src/main/java/org/apache/ctakes/core/cr/AbstractFileTreeReader.java

But the error isn't resolved yet. 

Thanks for any help you can provide.

**Comment by reckart** [comment]
Try adding the workaround to the `PiperFileRunner`.

**Comment by silwalr** [comment]
@reckart  Amazing. That resolved it! Thank you so much!

**Comment by seanfinan** [comment]
@silwalr Can you tell me where you inserted the line in PiperFileRunner?

**Comment by silwalr** [comment]
@seanfinan Here's a screen grab of inline diff of my fix: 
![image](https://github.com/user-attachments/assets/8a681354-d4d2-43c9-9031-2acf14200408)

**Comment by seanfinan** [comment]
Cheers!
